# Generated by Django 3.2.5 on 2022-02-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='area_hectacres',
            new_name='area_hectares',
        ),
        migrations.AddField(
            model_name='site',
            name='justification',
            field=models.TextField(null=True),
        ),
    ]
